# Generated by Django 3.0.6 on 2020-09-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DropSuggestionModel',
            fields=[
                ('suggestiontId', models.AutoField(primary_key=True, serialize=False)),
                ('suggestorEmailId', models.CharField(max_length=200)),
                ('suggestiontText', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='KeepMeUpdatedEmail',
            fields=[
                ('newsletterId', models.AutoField(primary_key=True, serialize=False)),
                ('newsletterEmailId', models.CharField(max_length=200)),
            ],
        ),
    ]
