# Generated by Django 3.0.6 on 2020-08-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechDeciphers_Leaks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaks',
            name='leakImage',
            field=models.ImageField(blank=True, null=True, upload_to='TechDeciphers_Leaks'),
        ),
    ]
