# Generated by Django 3.0.6 on 2021-02-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notebooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='notebook_image',
            field=models.ImageField(blank=True, null=True, upload_to='Notebooks'),
        ),
    ]
