# Generated by Django 3.0.6 on 2020-06-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechDeciphers_Gadgets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gadgets',
            name='gadgetImage',
            field=models.ImageField(upload_to='MediaFolder/TechDeciphers_Gadgets'),
        ),
    ]
