# Generated by Django 3.0.6 on 2020-06-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechDeciphers_Gadgets', '0002_auto_20200610_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gadgets',
            name='gadgetImage',
            field=models.ImageField(upload_to='TechDeciphers_Gadgets'),
        ),
    ]
