# Generated by Django 3.0.6 on 2020-07-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechDeciphers_Gadgets', '0004_auto_20200610_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gadgets',
            name='gadgetImage',
            field=models.ImageField(upload_to='TechDeciphers_Gadgets'),
        ),
    ]
