# Generated by Django 3.0.6 on 2020-07-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechDeciphers_Gadgets', '0005_auto_20200711_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gadgets',
            name='gadgetImage',
            field=models.ImageField(blank=True, upload_to='TechDeciphers_Gadgets'),
        ),
    ]
