# Generated by Django 3.0.6 on 2020-07-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechDeciphers_Gadgets', '0006_auto_20200713_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gadgets',
            name='gadgetImage',
            field=models.ImageField(blank=True, null=True, upload_to='TechDeciphers_Gadgets'),
        ),
    ]
