# Generated by Django 3.0.6 on 2020-08-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechDeciphers_Gadgets', '0008_auto_20200718_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='gadgets',
            name='isPublished',
            field=models.BooleanField(default=False),
        ),
    ]
