# Generated by Django 3.0.6 on 2020-07-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechDeciphers_News', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='newsImage',
            field=models.ImageField(upload_to='TechDeciphers_News'),
        ),
    ]
