# Generated by Django 3.0.6 on 2020-08-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechDeciphers_News', '0002_auto_20200711_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='newsImage',
            field=models.ImageField(blank=True, null=True, upload_to='TechDeciphers_News'),
        ),
    ]
