# Generated by Django 3.0.6 on 2020-08-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechDeciphers_News', '0003_auto_20200815_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='isPublished',
            field=models.BooleanField(default=False),
        ),
    ]
